version: 2

jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
      - image: circleci/node
        command: [yarn]
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
