version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:jdk-node
    steps:
      - checkout
      # Install yarn
      - run: curl -o- -L https://yarnpkg.com/install.sh | bash
      - run: yarn install
      - run: yarn build
