(ns ngame.common.constants)

(defonce movement-speed 100)
(defonce spacing 10)
(defonce height 480)
(defonce width 600)
(defonce key-evt "key-event")
(defonce key-up-evt "key-up")
(defonce key-down-evt "key-down")
(defonce game-update-evt "game-update")
(defonce game-update-interval 100)
